In [3]:
# exploratory data analysis

In [5]:
# importing packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import ipywidgets as widgets
from IPython.display import display

In [6]:
# reading in data and identifying numeric data and categorical/binary data

df = pd.read_csv('/Users/22holleranm/bios635/Train1.csv', encoding='latin1')

numeric_cols = ['HOSPNUM', 'RDELAY', 'AGE', 'RSBP', 'HOURLOCAL', 'MINLOCAL', 'ONDRUG', 
    'DMAJNCHD', 'DSIDED', 'DRSISCD', 'DRSHD', 'DRSUNKD', 'DPED', 'DALIVED', 'DDEADD',
    'FLASTD', 'FDEADC', 'FU1_RECD', 'FU2_DONE', 'FU1_COMP', 'TD', 'EXPDD', 'EXPD6', 'EXPD14',
]

categorical_cols = ['RCONSC', 'SEX','RSLEEP', 'RATRIAL', 'RCT', 
    'RVISINF', 'RHEP24', 'RASP3', 'RDEF1', 'RDEF2', 'RDEF3', 'RDEF4', 'RDEF5',
    'RDEF6', 'RDEF7', 'RDEF8', 'STYPE', 'DAYLOCAL', 'RXASP', 'RXHEP', 'DASP14', 
    'DASPLT', 'DLH14', 'DMH14', 'DHH14', 'DSCH', 'DIVH', 'DAP', 'DOAC', 'DGORM', 
    'DSTER', 'DCAA', 'DHAEMD', 'DCAREND', 'DTHROMB', 'DMAJNCH', 'DSIDE', 'DDIAGISC', 
    'DDIAGHA', 'DDIAGUN', 'DNOSTRK', 'DRSISC', 'DRSH', 'DRSUNK', 'DPE', 'DALIVE',
    'DPLACE', 'DDEAD', 'DDEADC', 'FDEAD', 'FRECOVER', 'FDENNIS', 'FPLACE',
    'FAP', 'FOAC', 'COUNTRY', 'CNTRYNUM', 'CMPLASP', 'CMPLHEP', 'ID', 'SET14D', 
    'ID14', 'OCCODE', 'DEAD1', 'DEAD2', 'DEAD3', 'DEAD4', 'DEAD5', 'DEAD6', 'DEAD7', 
    'DEAD8', 'H14', 'ISC14', 'NK14', 'STRK14', 'HTI14', 'PE14', 'DVT14', 'TRAN14', 'NCB14' 
]

/var/folders/zy/kq72dddn62n0l225t1mm0w9m0000gr/T/ipykernel_66093/1502538382.py:3: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/22holleranm/bios635/Train1.csv', encoding='latin1')

In [7]:
# plotting histograms with density lines for numeric variables

def plot_num(col):
    if col in df.columns and df[col].dropna().nunique() > 1:
        plt.figure(figsize=(8, 4))
        sns.distplot(df[col].dropna(), hist_kws=dict(linewidth=1, edgecolor='k'), bins=20)
        plt.title(f'Density Plot for {col}')
        plt.xlabel(col)
        plt.tight_layout()
        plt.ylabel('Density')
        plt.show()

dropdown = widgets.Dropdown(options=numeric_cols, description='Variable:')
widgets.interact(plot_num, col=dropdown)

interactive(children=(Dropdown(description='Variable:', options=('HOSPNUM', 'RDELAY', 'AGE', 'RSBP', 'HOURLOCA…

In [8]:
# plotting pie charts for categorial/binary variables

def plot_cat(col):
    plt.figure(figsize=(6, 6))
    df[col].value_counts(dropna=False).plot.pie(
        autopct='%1.1f%%',
        startangle=90,
        wedgeprops=dict(width=0.5)
    )
    plt.title(f'Pie Chart of {col}')
    plt.ylabel('')
    plt.tight_layout()
    plt.show()

dropdown = widgets.Dropdown(options=categorical_cols, description='Variable:')
widgets.interact(plot_cat, col=dropdown)

interactive(children=(Dropdown(description='Variable:', options=('RCONSC', 'SEX', 'RSLEEP', 'RATRIAL', 'RCT', …

In [9]:
# cleaning data and numerically coding categorial variables

df_encoded = df.copy()

encoding_maps = {}

for col in categorical_cols:
    if col in df_encoded.columns:
        df_encoded[col], mapping = pd.factorize(df_encoded[col], sort=True)
        encoding_maps[col] = dict(enumerate(mapping))
    else:
        print(f"Column '{col}' not found in DataFrame — skipping.")

df_clean = df_encoded

print(df_clean.head())

   ID  HOSPNUM  RDELAY  RCONSC  SEX  AGE  RSLEEP  RATRIAL  RCT  RVISINF  ...  \
0   0        1      17       0    1   69       1       -1    1        1  ...
1   1        1      10       1    1   76       1       -1    1        0  ...
2   2        1      24       1    1   23       0       -1    1        0  ...
3   3        1       5       0    0   83       0       -1    0        0  ...
4   4        1       8       0    0   64       1       -1    1        1  ...

   DEAD8  H14  ISC14  NK14  STRK14  HTI14  PE14  DVT14  TRAN14  NCB14
0      0    0      0     0       0      0     0      0       0      0
1      0    0      0     0       0      0     0      0       0      0
2      0    0      0     0       0      0     0      0       0      0
3      0    0      0     0       0      0     0      0       0      0
4      0    0      0     0       0      0     0      0       0      0

[5 rows x 113 columns]

In [ ]:
# creating correlation matrix for numeric variables

df[numeric_cols].corr()

,HOSPNUM,RDELAY,AGE,RSBP,HOURLOCAL,MINLOCAL,ONDRUG,DMAJNCHD,DSIDED,DRSISCD,...,DDEADD,FLASTD,FDEADC,FU1_RECD,FU2_DONE,FU1_COMP,TD,EXPDD,EXPD6,EXPD14
HOSPNUM,1.000000,0.040023,-0.025680,-0.002524,-0.160622,-0.085130,-0.069150,0.143066,-0.030059,-0.017087,...,0.022615,NaN,0.009879,0.064012,0.008491,0.036597,0.008056,0.009471,0.001609,0.011237
RDELAY,0.040023,1.000000,-0.007604,-0.032486,-0.038436,-0.012586,-0.015971,0.132635,-0.029069,-0.025151,...,-0.009618,NaN,0.016888,-0.001069,0.049714,0.012157,0.053231,-0.096263,-0.090458,-0.095106
AGE,-0.025680,-0.007604,1.000000,0.090078,0.001452,-0.004619,0.091089,0.063668,-0.027428,-0.029860,...,0.064984,NaN,-0.013978,0.014286,-0.102241,0.033714,-0.197314,0.604616,0.580301,0.348561
RSBP,-0.002524,-0.032486,0.090078,1.000000,0.008325,-0.002236,0.023530,0.065061,-0.014147,0.032696,...,-0.042782,NaN,-0.055624,0.001095,0.005833,-0.000278,0.018528,-0.024775,-0.010848,-0.026721
HOURLOCAL,-0.160622,-0.038436,0.001452,0.008325,1.000000,0.426614,0.015947,-0.039176,0.012036,0.074949,...,0.023180,NaN,-0.005234,-0.003774,0.034882,0.034964,0.000104,-0.014929,-0.014291,-0.018734
MINLOCAL,-0.085130,-0.012586,-0.004619,-0.002236,0.426614,1.000000,0.001643,-0.008136,0.078600,-0.021465,...,-0.011107,NaN,-0.001791,-0.002105,0.006399,-0.003878,-0.014576,-0.000622,-0.003221,-0.005553
ONDRUG,-0.069150,-0.015971,0.091089,0.023530,0.015947,0.001643,1.000000,0.164713,0.112004,0.088901,...,0.431259,NaN,0.196685,0.055315,0.207166,0.082134,0.168966,0.148934,0.073907,0.036424
DMAJNCHD,0.143066,0.132635,0.063668,0.065061,-0.039176,-0.008136,0.164713,1.000000,0.816497,0.804093,...,0.829431,NaN,-0.155037,0.522528,0.346903,0.671519,0.346761,0.056534,0.060643,0.032518
DSIDED,-0.030059,-0.029069,-0.027428,-0.014147,0.012036,0.078600,0.112004,0.816497,1.000000,0.577574,...,0.373580,NaN,0.185505,0.083338,0.025725,-0.012521,0.047735,-0.032378,-0.047309,-0.039000
DRSISCD,-0.017087,-0.025151,-0.029860,0.032696,0.074949,-0.021465,0.088901,0.804093,0.577574,1.000000,...,0.354383,NaN,0.094299,0.431791,0.010145,0.432461,0.010747,-0.079387,-0.024401,-0.001827
DRSHD,0.060922,0.331818,0.036196,-0.009227,-0.001527,-0.235546,0.377964,0.075858,0.731950,0.866025,...,0.807214,NaN,0.012172,0.043021,0.069405,0.055327,-0.018728,-0.026832,-0.125378,-0.178788
DRSUNKD,0.188471,-0.077978,0.021124,0.034790,0.056477,-0.027096,0.271153,NaN,-0.152685,NaN,...,0.738045,NaN,-0.129434,0.256192,0.193629,0.195140,0.153962,0.020255,0.074231,0.070455
DPED,-0.015962,-0.192662,0.014306,0.050704,0.036766,0.073136,0.475490,NaN,1.000000,NaN,...,0.935123,NaN,0.191369,0.350835,0.062838,0.381709,0.016301,0.035982,0.006932,-0.010118
DALIVED,-0.005045,-0.026186,0.067888,0.017057,0.002165,-0.005971,0.469519,0.955788,0.321436,0.046237,...,NaN,NaN,-0.024059,0.347959,0.068186,0.382582,0.049348,0.184406,0.158721,0.151722
DDEADD,0.022615,-0.009618,0.064984,-0.042782,0.023180,-0.011107,0.431259,0.829431,0.373580,0.354383,...,1.000000,NaN,0.143925,0.471266,0.408518,0.502086,1.000000,-0.026721,-0.038505,-0.064525
FLASTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FDEADC,0.009879,0.016888,-0.013978,-0.055624,-0.005234,-0.001791,0.196685,-0.155037,0.185505,0.094299,...,0.143925,NaN,1.000000,0.034954,0.211739,0.013723,0.245196,-0.219958,-0.194774,-0.207250
FU1_RECD,0.064012,-0.001069,0.014286,0.001095,-0.003774,-0.002105,0.055315,0.522528,0.083338,0.431791,...,0.471266,NaN,0.034954,1.000000,0.200539,0.850602,0.117454,0.024201,0.016455,0.015124
FU2_DONE,0.008491,0.049714,-0.102241,0.005833,0.034882,0.006399,0.207166,0.346903,0.025725,0.010145,...,0.408518,NaN,0.211739,0.200539,1.000000,0.158625,0.785514,-0.217188,-0.260403,-0.263208
FU1_COMP,0.036597,0.012157,0.033714,-0.000278,0.034964,-0.003878,0.082134,0.671519,-0.012521,0.432461,...,0.502086,NaN,0.013723,0.850602,0.158625,1.000000,0.080927,0.044187,0.038809,0.032869
TD,0.008056,0.053231,-0.197314,0.018528,0.000104,-0.014576,0.168966,0.346761,0.047735,0.010747,...,1.000000,NaN,0.245196,0.117454,0.785514,0.080927,1.000000,-0.333518,-0.384420,-0.368152
EXPDD,0.009471,-0.096263,0.604616,-0.024775,-0.014929,-0.000622,0.148934,0.056534,-0.032378,-0.079387,...,-0.026721,NaN,-0.219958,0.024201,-0.217188,0.044187,-0.333518,1.000000,0.866653,0.760954
EXPD6,0.001609,-0.090458,0.580301,-0.010848,-0.014291,-0.003221,0.073907,0.060643,-0.047309,-0.024401,...,-0.038505,NaN,-0.194774,0.016455,-0.260403,0.038809,-0.384420,0.866653,1.000000,0.941868
EXPD14,0.011237,-0.095106,0.348561,-0.026721,-0.018734,-0.005553,0.036424,0.032518,-0.039000,-0.001827,...,-0.064525,NaN,-0.207250,0.015124,-0.263208,0.032869,-0.368152,0.760954,0.941868,1.000000

In [21]:
# data cleaning code to use at start of each model/analysis

# bring in data
train = pd.read_csv('/Users/22holleranm/bios635/Train1.csv', encoding='latin1')

# all numeric cols
numeric_cols = ['HOSPNUM', 'RDELAY', 'AGE', 'RSBP', 'HOURLOCAL', 'MINLOCAL', 'ONDRUG', 
    'DMAJNCHD', 'DSIDED', 'DRSISCD', 'DRSHD', 'DRSUNKD', 'DPED', 'DALIVED', 'DDEADD',
    'FLASTD', 'FDEADC', 'FU1_RECD', 'FU2_DONE', 'FU1_COMP', 'TD', 'EXPDD', 'EXPD6', 'EXPD14',
]

# all cat calls
categorical_cols = ['RCONSC', 'SEX','RSLEEP', 'RATRIAL', 'RCT', 
    'RVISINF', 'RHEP24', 'RASP3', 'RDEF1', 'RDEF2', 'RDEF3', 'RDEF4', 'RDEF5',
    'RDEF6', 'RDEF7', 'RDEF8', 'STYPE', 'DAYLOCAL', 'RXASP', 'RXHEP', 'DASP14', 
    'DASPLT', 'DLH14', 'DMH14', 'DHH14', 'DSCH', 'DIVH', 'DAP', 'DOAC', 'DGORM', 
    'DSTER', 'DCAA', 'DHAEMD', 'DCAREND', 'DTHROMB', 'DMAJNCH', 'DSIDE', 'DDIAGISC', 
    'DDIAGHA', 'DDIAGUN', 'DNOSTRK', 'DRSISC', 'DRSH', 'DRSUNK', 'DPE', 'DALIVE',
    'DPLACE', 'DDEAD', 'DDEADC', 'FDEAD', 'FRECOVER', 'FDENNIS', 'FPLACE',
    'FAP', 'FOAC', 'COUNTRY', 'CNTRYNUM', 'CMPLASP', 'CMPLHEP', 'ID', 'SET14D', 
    'ID14', 'OCCODE', 'DEAD1', 'DEAD2', 'DEAD3', 'DEAD4', 'DEAD5', 'DEAD6', 'DEAD7', 
    'DEAD8', 'H14', 'ISC14', 'NK14', 'STRK14', 'HTI14', 'PE14', 'DVT14', 'TRAN14', 'NCB14' 
]

# encoding cat variables to be numeric
train_encoded = train.copy()

encoding_maps = {}

for col in categorical_cols:
    if col in train_encoded.columns:
        train_encoded[col], mapping = pd.factorize(train_encoded[col], sort=True)
        encoding_maps[col] = dict(enumerate(mapping))
    else:
        print(f"Column '{col}' not found in DataFrame — skipping.")

train_clean = train_encoded


# dropping unnecessary columns
train_clean = train_clean.drop(['ID', 'RDATE', 'DMAJNCHX', 'DSIDEX', 'DNOSTRKX', 'DDEADX', 'FDEADX', 'NCCODE', 'DDEAD', 'DDEADC', 'FDEADC', 'DDEADD', 'DDEADC', ], axis =1)

train_clean.head()

# FDEAD IS ENCODED AS N = 0, Y = 1, U = 2

/var/folders/zy/kq72dddn62n0l225t1mm0w9m0000gr/T/ipykernel_66093/341550774.py:4: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv('/Users/22holleranm/bios635/Train1.csv', encoding='latin1')

,HOSPNUM,RDELAY,RCONSC,SEX,AGE,RSLEEP,RATRIAL,RCT,RVISINF,RHEP24,...,DEAD8,H14,ISC14,NK14,STRK14,HTI14,PE14,DVT14,TRAN14,NCB14
0,1,17,0,1,69,1,-1,1,1,-1,...,0,0,0,0,0,0,0,0,0,0
1,1,10,1,1,76,1,-1,1,0,-1,...,0,0,0,0,0,0,0,0,0,0
2,1,24,1,1,23,0,-1,1,0,-1,...,0,0,0,0,0,0,0,0,0,0
3,1,5,0,0,83,0,-1,0,0,-1,...,0,0,0,0,0,0,0,0,0,0
4,1,8,0,0,64,1,-1,1,1,-1,...,0,0,0,0,0,0,0,0,0,0